name: fast_hash
description: A collection of fast non-cryptographic hash functions.
version: 0.0.1
homepage: https://github.com/raycardillo/dart_fast_hash
repository: https://github.com/raycardillo/dart_fast_hash

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  fixnum: ^1.0.0

dev_dependencies:
  test: ^1.16.0
  lints: ^1.0.1
